export const access = "public";

export default async function (req, res) {
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.send(`<!doctype html>
<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>NØPE — Voice</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:#f6f7f9;color:#111}.wrap{max-width:1180px;margin:auto;padding:30px 22px}.brand{font-weight:850;letter-spacing:.3px}.grid{display:grid;grid-template-columns:420px 1fr;gap:18px;margin-top:22px}.card{background:#fff;border:1px solid #e4e7ec;border-radius:22px;padding:24px;box-shadow:0 12px 40px #0000000a}.card h1{font-size:34px;margin:8px 0}.sub{color:#667085;line-height:1.5}.mic{width:112px;height:112px;border-radius:50%;border:0;background:#111;color:#fff;font-size:40px;cursor:pointer;display:block;margin:26px auto 12px}.mic.recording{background:#d92d20;animation:pulse 1.2s infinite}.hint{text-align:center;color:#777;font-size:14px}@keyframes pulse{50%{transform:scale(1.06)}}.box{margin-top:20px;background:#f8f9fb;border-radius:15px;padding:14px;min-height:68px}.label{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#98a2b3;font-weight:750}.transcript{font-size:17px;margin-top:6px}.actions{display:flex;gap:8px;margin-top:14px;flex-wrap:wrap}.btn{border:1px solid #ddd;background:#fff;border-radius:11px;padding:10px 13px;font-weight:700;cursor:pointer}.primary{background:#111;color:#fff;border-color:#111}.status{margin-top:14px;font-size:14px;color:#667085}.ok{color:#087443}.err{color:#b42318}audio{width:100%;margin-top:14px}.note{margin-top:18px;padding:13px;border-radius:13px;background:#f1f2f4;color:#667085;font-size:12px;line-height:1.5}.workflow{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:16px 0 20px}.node{border:1px solid #dfe3e8;border-radius:12px;padding:10px 12px;background:#fff;font-size:12px;font-weight:750}.node.live{border-color:#111;box-shadow:0 0 0 3px #1111110b}.arrow{color:#98a2b3}.stage{margin-top:16px;padding:13px 14px;border-radius:13px;background:#f8f9fb;border-left:3px solid #d0d5dd}.stage b{display:block;font-size:13px}.stage span{font-size:12px;color:#667085}.catalogue{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.product{border:1px solid #e4e7ec;border-radius:14px;padding:13px;background:#fff}.product .pname{font-size:13px;font-weight:750}.product .price{font-weight:800;margin-top:7px}.tag{display:inline-block;font-size:10px;background:#f2f4f7;border-radius:999px;padding:4px 7px;margin-top:7px}.memory{margin-top:14px;padding:12px;border-radius:12px;background:#fff9e8;border:1px solid #f3df9a;font-size:12px}.timeline{display:grid;gap:8px;margin-top:12px}.event{display:flex;gap:10px;align-items:flex-start;font-size:12px;color:#667085}.dot{width:8px;height:8px;border-radius:50%;background:#98a2b3;margin-top:4px;flex:none}.dot.on{background:#111}.sectionTitle{font-size:14px;font-weight:800;margin-top:4px}@media(max-width:900px){.grid{grid-template-columns:1fr}.catalogue{grid-template-columns:1fr 1fr}}
</style></head><body><div class="wrap"><div class="brand">NØPE · LIVE AGENT DEMO</div><div class="grid"><div class="card">
<div class="label">Gnani voice input</div><h1>Talk to NØPE.</h1><div class="sub">Voice-first personal commerce decision agent. Speak naturally in Hindi, English or Hinglish.</div>
<button id="mic" class="mic">🎙</button><div id="hint" class="hint">Click to start speaking</div>
<div class="box"><div class="label">Transcript</div><div id="transcript" class="transcript">—</div></div>
<div class="actions"><button id="copy" class="btn">Copy transcript</button><button id="open" class="btn primary">Open AgenticOrg</button><button id="speak" class="btn">🔊 Replay</button></div>
<div id="status" class="status"></div><audio id="audio" controls hidden></audio>
<div class="note"><b>Demo:</b> The visual panel shows the live decision flow executed by the NØPE demo bridge: Gnani → NØPE decision layer → preference memory → catalogue search/ranking → TTS.</div>
</div><div class="card"><div class="sectionTitle">Agentic commerce workflow</div><div class="workflow"><div id="nGnani" class="node">Gnani STT</div><div class="arrow">→</div><div id="nAgent" class="node">NØPE / AgenticOrg</div><div class="arrow">→</div><div id="nMemory" class="node">Preference Memory</div><div class="arrow">→</div><div id="nCatalog" class="node">Product Catalogue</div><div class="arrow">→</div><div id="nTts" class="node">Gnani TTS</div></div>
<div class="stage"><b id="stageTitle">Waiting for voice input</b><span id="stageDetail">Your next interaction will animate through the workflow.</span></div>
<div class="memory"><b>Preference memory</b><div id="memoryText">No new signal yet.</div></div>
<div class="label" style="margin-top:20px">Live shortlist</div><div id="catalogue" class="catalogue"><div class="product"><div class="pname">Waiting for search…</div><span class="tag">catalogue</span></div></div>
<div class="label" style="margin-top:20px">Agent event stream</div><div id="timeline" class="timeline"><div class="event"><span class="dot"></span><span>Demo ready — awaiting user intent.</span></div></div>
<div class="note"><b>Partner rails:</b> Gnani = voice I/O · AgenticOrg = agent runtime/configuration · mock catalogue = product discovery/ranking · Delhivery = delivery rail · Pine Labs = payment rail. This page is the visual demo surface; AgenticOrg itself remains the configured agent.</div>
</div></div>
<script>
const $=function(id){return document.getElementById(id)}; const mic=document.getElementById("mic"),hint=document.getElementById("hint"),transcriptEl=document.getElementById("transcript"),statusEl=document.getElementById("status"),audio=document.getElementById("audio");let recorder,chunks=[],recording=false,transcript="";
function setStatus(t,c){statusEl.textContent=t;statusEl.className="status "+(c||"")} function stage(t,d,n){$("stageTitle").textContent=t;$("stageDetail").textContent=d;["nGnani","nAgent","nMemory","nCatalog","nTts"].forEach(function(x){$(x).classList.remove("live")});if(n)$(n).classList.add("live");var e=document.createElement("div");e.className="event";e.innerHTML="<span class=\"dot on\"></span><span><b>"+t+"</b> — "+d+"</span>";$("timeline").prepend(e)} function showProducts(items){$("catalogue").innerHTML=items.slice(0,4).map(function(p){return "<div class=\"product\"><div class=\"pname\">"+p.name+"</div><div class=\"price\">₹"+p.price+"</div><span class=\"tag\">"+(p.category||"shirt")+" · ranked</span></div>"}).join("")||"<div class=\"product\"><div class=\"pname\">No matching products</div><span class=\"tag\">search complete</span></div>"}
function audioBufferToWav(b){const r=b.sampleRate,n=b.length,o=new ArrayBuffer(44+n*2),v=new DataView(o),w=(p,s)=>{for(let i=0;i<s.length;i++)v.setUint8(p+i,s.charCodeAt(i))};w(0,"RIFF");v.setUint32(4,36+n*2,true);w(8,"WAVE");w(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,r,true);v.setUint32(28,r*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,"data");v.setUint32(40,n*2,true);const c=b.getChannelData(0);let p=44;for(let i=0;i<n;i++){let s=Math.max(-1,Math.min(1,c[i]));v.setInt16(p,s<0?s*32768:s*32767,true);p+=2}return new Blob([o],{type:"audio/wav"})}
function b64(blob){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result.split(",")[1]);r.onerror=no;r.readAsDataURL(blob)})}
async function gnani(name,args){const r=await fetch("/api/mcp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:Date.now(),method:"tools/call",params:{name,arguments:args}})});const j=await r.json();if(j.error)throw Error(j.error.message||"MCP error");const t=j.result?.content?.find(x=>x.type==="text")?.text;return t?JSON.parse(t):j.result}
async function runNopeVoice(){
  stage("NØPE is interpreting intent","Extracting category, occasion, budget and exclusions.","nAgent"); setStatus("NØPE is thinking…");
  const q=transcript.toLowerCase();
  const budgetMatch=q.match(/(?:₹|rs\.?|rupees?\s*)([0-9,]+)/i);
  const budget=budgetMatch?Number(budgetMatch[1].replace(/,/g,"")):3000;
  const category=/shirt|clothing|top/.test(q)?"clothing":"shirt";
  const occasion=/wedding|shaadi|marriage/.test(q)?"wedding":null;
  const avoid=[/shiny|chamak|silk/.test(q)?"shiny":null,/formal|uncle/.test(q)?"formal":null].filter(Boolean).join(",");
  const style=/relaxed|casual|chill|youthful|stylish/.test(q)?"classy relaxed":(/classy/.test(q)?"classy":null);
  stage("Reading preference memory","Retrieving learned likes, dislikes and rejection signals.","nMemory"); const prefs=await gnani("get_preferences",{user_id:"demo-user"}); $("memoryText").textContent=(prefs.preferences||[]).slice(0,4).map(function(p){return (p.preference||"signal")+": "+(p.value||"")}).join(" · ")||"No stored preference signal yet."; stage("Searching product catalogue","Filtering the mock catalogue against the current intent.","nCatalog"); const found=await gnani("search_products",{category,max_price:budget,occasion,style,avoid});
  const products=found.results||[]; showProducts(products); stage("Ranking candidate products","Comparing returned catalogue items against current intent and memory.","nCatalog"); let ranked=products;
  if(products.length) {
    const rr=await gnani("rank_products",{products,preferences:prefs.preferences||[],intent:transcript});
    ranked=rr.results||products;
  }
  if(!ranked.length){
    var reply="Mujhe abhi aapki requirements ke saath koi suitable option nahi mila. Aap budget ya style mein kya change karna chahenge?";
  } else {
    const picks=ranked.slice(0,3);
    reply="Bilkul. Maine aapke liye "+picks.length+" options shortlist kiye. "+picks.map((p,i)=>(i+1)+". "+p.name+" — ₹"+p.price).join(". ")+" . Ye options aapki current requirements ke closest hain.";
  }
  transcriptEl.textContent=transcript;
  setStatus("NØPE found the options. Speaking…","ok"); stage("Generating NØPE voice response","Sending the final decision to Gnani TTS.","nTts"); const t=await gnani("gnani_text_to_speech",{text:reply,language:"hi-IN",voice:"Nalini",speed:1});
  if(!t.success) throw Error(t.error||"TTS failed");
  if(!t.audio_base64) throw Error("NØPE TTS returned no audio"); const bin=atob(t.audio_base64); const arr=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++) arr[i]=bin.charCodeAt(i); const audioBlob=new Blob([arr],{type:t.audio_content_type||"audio/wav"}); if(audio._objectUrl) URL.revokeObjectURL(audio._objectUrl); audio._objectUrl=URL.createObjectURL(audioBlob); audio.src=audio._objectUrl; audio.load(); audio.hidden=false; await new Promise((resolve,reject)=>{audio.oncanplay=resolve;audio.onerror=()=>reject(Error("NØPE audio could not be decoded by the browser"));}); await audio.play();
  hint.textContent="NØPE replied — click 🎙️ to speak again";
  setStatus("✓ Full voice loop complete","ok");
}
async function start(){const stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);chunks=[];recording=true;mic.classList.add("recording");hint.textContent="Listening… click again to stop";recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());mic.classList.remove("recording");hint.textContent="Processing with Gnani…";stage("Gnani is transcribing","Converting your voice into text.","nGnani");try{const blob=new Blob(chunks,{type:recorder.mimeType}),ctx=new AudioContext(),decoded=await ctx.decodeAudioData(await blob.arrayBuffer()),wav=audioBufferToWav(decoded);await ctx.close();const r=await gnani("gnani_speech_to_text",{audio_base64:await b64(wav),language_code:"hi-IN",preferred_language:"hi-IN",format:"transcribe"});if(!r.success)throw Error(r.error||("Gnani STT failed: "+r.status_code));transcript=typeof r.transcript==="string"?r.transcript:JSON.stringify(r.transcript);transcriptEl.textContent=transcript||"No speech detected";hint.textContent="Transcript received — NØPE is thinking";setStatus("✓ Gnani STT worked","ok");await runNopeVoice()}catch(e){hint.textContent="Try again";setStatus("Voice loop error: "+e.message,"err")}};recorder.start()}
mic.onclick=async()=>{try{if(!recording)await start();else{recording=false;recorder.stop()}}catch(e){recording=false;mic.classList.remove("recording");setStatus(e.message,"err")}};
document.getElementById("copy").onclick=async()=>{if(transcript){await navigator.clipboard.writeText(transcript);setStatus("✓ Transcript copied.","ok")}};
document.getElementById("open").onclick=async()=>{if(transcript)await navigator.clipboard.writeText(transcript);window.open("https://agenticorg.hackathon.pinelabs.com/dashboard/agents","_blank");setStatus("✓ Transcript copied. Paste into NØPE Chat.","ok")};
document.getElementById("speak").onclick=async()=>{if(!transcript){setStatus("Speak first.","err");return}try{setStatus("Generating Gnani TTS…");const r=await gnani("gnani_text_to_speech",{text:transcript,language:"hi-IN",voice:"Nalini",speed:1});if(!r.success)throw Error(r.error||"TTS failed");audio.src=r.audio_url;audio.hidden=false;await audio.play();setStatus("✓ Gnani TTS worked","ok")}catch(e){setStatus("TTS error: "+e.message,"err")}};
</script></body></html>`);
}